version: '3'
services:
    php-apache:
        build: .
        ports:
            - 80:80
        volumes:
            - ./DocumentRoot:/var/www/html
        links:
            - 'mariadb'
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: rootpwd
        ports:
            - 8080:80
        links:
            - mariadb:mysql

    mariadb:
        image: mariadb:10.1
        ports:
            - 3306:3306
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/Minsk"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'

volumes:
    mariadb: